### ISSUE TITLE
Cleanup result from redis when creation is fetched succesfully

### ISSUE THREAD

**Issue by one1zero1one** [abraham-ai/eden#37]
Redis instance is growing indefinitely with the temporarily stored outputs (creations).
A good way to control this is to remove from redis the creation after is successfully retrieved by the client.

**Comment by Mayukhdeb** [comment]
An easier approach would be to make a new utility called `/delete` which takes in the token as input and deletes the corresponding result if it exists.

Then we can just run delete right after `/fetch` from the client side :slightly_smiling_face:

**Comment by one1zero1one** [comment]
IMHO, client shouldn't be responsible with `eden`'s internal systems - that is one of the reasons to trust `eden`. Much like when you buy something from a shop you're not responsible for updating their inventory :)

Deleting the successfully shipped creations from the temporary storage (Redis) is inherently part of eden, and should not be decoupled from `/fetch`.

**Comment by Mayukhdeb** [comment]
So the ideal way to implement this would be to make a new method on the `ResultStorage` class like `ResultStorage.delete(token = token)` and then whenever someone runs `/fetch` we can check the status and if `status ==  'complete'` we delete the results

I think this feature should also be optional as an arg in host_block, just for the sake of flexibility. 
```python
host_block(block = eden_block, remove_result_on_fetch = True, **kwargs)
```

**Comment by Mayukhdeb** [comment]
Update:
The user can now set `remove_result_on_fetch = True` on `host_block`. This will delete the result once the task is complete and the user fetches the output (after returning the output ofc)

**Comment by Mayukhdeb** [comment]
If the user tries to fetch a completed and deleted job, eden returns `{'status': 'removed'}`

**Comment by Mayukhdeb** [comment]
Todo for closing this issue:
*  I make a small release with this feature :heavy_check_mark:
* @one1zero1one tries it out on our deployments and makes sure it actually works :slightly_smiling_face: 
* I add in some test cases
